version: '3'
services:
  database:
    build: ./database/
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  webserver:
    build: ./webserver/
    ports:
      - 5000:5000

